---
- name: Check if composer is already installed
  stat:
    path: /usr/local/bin/composer
  register: composer_check

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'
  when: not composer_check.stat.exists

- name: Install Composer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  when: not composer_check.stat.exists