---
- name: "Check if {{ abs_path }} directory exists"
  stat:
    path: "{{ abs_path }}"
  register: repo_cloned

- name: Clone ABS repository
  git:
    repo: "{{ abs_repo_url }}"
    dest: "{{ abs_path }}"
  when: not repo_cloned.stat.exists

- name: Check if node_modules exists
  stat:
    path: "{{ abs_path }}/node_modules"
  register: npm_installed

- name: Run npm install
  shell: |
    if [ -d {{ abs_path }} ]; then
      cd {{ abs_path }} && npm install
    fi
  when: not npm_installed.stat.exists

- name: Run npm update @mtproto/core
  shell: |
    if [ -d {{ abs_path }} ]; then
      cd {{ abs_path }} && npm update @mtproto/core
    fi
  when: not npm_installed.stat.exists

- name: Generate the config.js file
  template:
    src: "{{ 'configm1.js.j2' if 'm1' in inventory_hostname else ('configm2.js.j2' if 'm2' in inventory_hostname else 'configm0.js.j2') }}"
    dest: "{{ abs_path }}/config.js"
    owner: root
    group: root
    mode: 0644
    backup: yes