---
- name: Ensure dependencies are installed
  apt:  # Проверка и установка каждого пакета
    name:
      - curl
      - wget
      - git
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - gnupg
      - sqlite3
      - unzip
    state: latest # Обновляет версию пакета если он уже установлен и доступна новая версия
    update_cache: true # Обновление кэша перед установкой пакетов
    cache_valid_time: 3600 # Не будет обновлять если недавно обновляли