---
- name: Ensure dependencies are installed
  apt:
    name: tmux
    state: latest # Проверка на установку каждого пакета, также обновляет версию пакета если он уже установлен и доступна новая версия
    update_cache: true
    cache_valid_time: 3600

- name: Generate chatbot file
  template:
    src: chatbot.j2
    dest: "/etc/init.d/chatbot"
    owner: root
    group: root
    mode: "0755"

- name: Generate chatbot.service file
  template:
    src: chatbot.service.j2
    dest: "/etc/systemd/system/chatbot.service"
    owner: root
    group: root
    mode: "0644"

- name: Generate chatbot.timer file
  template:
    src: chatbot.timer.j2
    dest: "/etc/systemd/system/chatbot.timer"
    owner: root
    group: root
    mode: "0644"
