---
- name: Ensure directory for apt keyrings exist
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Check if Docker GPG key already present
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_gpg_key

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: not docker_gpg_key.stat.exists

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts.lsb.codename | lower }} stable"
    state: present
    filename: docker

- name: Update apt cache after adding NodeSource repository
  apt:
    update_cache: yes
    cache_valid_time: 0 # указан 0 для Force-обновления после добавлении репозитории
  when: not docker_gpg_key.stat.exists

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present