- name: Ensure /var/www/html directory exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data # Директорию будет использовать сервис Raptor на php и его пользователь www-data
    group: www-data
    mode: "0755"

- name: Generate interface.php file
  template:
    src: interface.php.j2
    dest: /var/www/html/interface.php
    owner: www-data
    group: www-data
    mode: "0644"

- name: Change owner of /var/www/html recursively
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
