---
- name: Deploy ABS
  gather_facts: true # Сбор данных о сервере
  hosts: webservers
  vars_files:
    - ../vars/vars.yml
  roles:
    - role: setupRaptor
      when: # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"

    - role: renewSSLCertificates
      when: # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"

    - role: setupABS
      when: # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"

    - role: setupHttpRiva
      when: # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"

    - role: setupChatBotService
      when: # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"