---
- name: Deploy BlackApp
  hosts: webservers
  gather_facts: true # Сбор данных о сервере

  roles:
    - role: installDocker
      when: ansible_facts.os_family == "Debian"
    # условие на уровне всего playbook, если сервер не Debian-based, то не будет запускаться

    - role: installApache
      when: ansible_facts.os_family == "Debian"
      # условие на уровне всего playbook, если сервер не Debian-based, то не будет запускаться