---
- name: Deploy ABS
  gather_facts: true # Сбор данных о сервере
  hosts: webservers
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Check OS compatibility
      debug:
        msg: "Incompatible OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}. Only Debian 11 is supported."
      when: ansible_distribution != "Debian" or ansible_distribution_major_version != "11"
      # условие на уровне всего playbook, если сервер не Debian 11, то не будет запускаться

    - name: Run roles if OS is Debian 11
      block:
        - name: Include setupRaptor role
          include_role:
            name: setupRaptor

        - name: Include renewSSLCertificates role
          include_role:
            name: renewSSLCertificates

        - name: Include setupABS role
          include_role:
            name: setupABS
          vars:
            abs_path: "/var/www/abs"

        - name: Include setupHttpRiva role
          include_role:
            name: setupHttpRiva

        - name: Include setupChatBotService role
          include_role:
            name: setupChatBotService
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "11"